CREATE TABLE "cafes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"occupancy" text NOT NULL,
	"distance" text NOT NULL,
	"price" text NOT NULL,
	"closing" text NOT NULL,
	"fit" text NOT NULL,
	"image_url" text,
	"address" text NOT NULL,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"wifi" text NOT NULL,
	"outlets" text NOT NULL,
	"atmosphere" text NOT NULL,
	"duration" text NOT NULL,
	"tagline" text NOT NULL,
	"live_status" text NOT NULL,
	"live_note" text NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"best_hours" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"amenities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"policies" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"reviews" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"published" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cafes_slug_unique" UNIQUE("slug"),
	CONSTRAINT "cafes_score_check" CHECK ("cafes"."score" BETWEEN 0 AND 100)
);
--> statement-breakpoint
CREATE INDEX "cafes_slug_idx" ON "cafes" USING btree ("slug");