/**
 * Emit the seed content as plain SQL on stdout, instead of connecting to a
 * database the way `db/seed.ts` does.
 *
 * The deployed Postgres has no published port (see DEPLOY.md), so seeding it
 * normally means either publishing the port temporarily or tunnelling — both of
 * which need the database password on the operator's machine. Emitting SQL lets
 * the statements be piped into `psql` on the server instead, where the
 * credentials already live:
 *
 *   pnpm db:seed:sql --events-only > /tmp/seed.sql
 *   scp /tmp/seed.sql <server>:/tmp/
 *   ssh <server> 'docker exec -i <pg-container> psql -U <user> -d <db> \
 *       -v ON_ERROR_STOP=1 --single-transaction < /tmp/seed.sql'
 *
 * Reads the same `db/seed-data.ts` as the real seed script, so the two cannot
 * drift apart.
 *
 * Flags mirror `db/seed.ts`:
 *   --events-only  Categories, events, and join rows only. No demo author,
 *                  announcement, or placeholder post.
 *   --no-truncate  Emit INSERTs only, no TRUNCATE. For first-time seeding of an
 *                  environment whose content tables are already empty: keeps
 *                  the statements non-destructive, so nothing can be lost if
 *                  the assumption is wrong. Re-running WILL fail on the events
 *                  slug unique constraint rather than silently duplicating.
 */
import { CATEGORIES, EVENTS } from "../db/seed-data";

const EVENTS_ONLY = process.argv.includes("--events-only");
const NO_TRUNCATE = process.argv.includes("--no-truncate");

/** Quote a string as a SQL literal (doubling single quotes). */
function lit(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

/** Quote a nullable number as a SQL literal. */
function num(value: number | null): string {
	return value === null ? "NULL" : String(value);
}

const out: string[] = [];

out.push("-- Generated by scripts/emit-seed-sql.ts — do not edit by hand.");
out.push(`-- mode: ${EVENTS_ONLY ? "events-only" : "full"}`);
out.push("");

if (NO_TRUNCATE) {
	// Non-destructive mode: assert the tables really are empty rather than
	// clearing them, so a wrong assumption aborts instead of deleting data.
	out.push("-- Guard: this mode only seeds empty tables; it never deletes.");
	out.push(`DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM events;
  IF n > 0 THEN
    RAISE EXCEPTION 'Refusing to seed: % event(s) already exist. Re-run without --no-truncate to replace them.', n;
  END IF;
END $$;`);
} else {
	out.push("-- Guard: the TRUNCATE below cascades to registrations.");
	out.push(`DO $$
DECLARE n integer;
BEGIN
  SELECT count(*) INTO n FROM registrations;
  IF n > 0 THEN
    RAISE EXCEPTION 'Refusing to seed: % registration(s) exist; TRUNCATE ... CASCADE would delete them.', n;
  END IF;
END $$;`);
	out.push("");
	out.push(
		EVENTS_ONLY
			? "TRUNCATE TABLE events, event_categories RESTART IDENTITY CASCADE;"
			: "TRUNCATE TABLE events, announcements, event_categories RESTART IDENTITY CASCADE;"
	);
}
out.push("");

out.push(`-- ${CATEGORIES.length} categories`);
for (const c of CATEGORIES) {
	out.push(
		`INSERT INTO categories (name, slug) VALUES (${lit(c.name)}, ${lit(c.slug)}) ON CONFLICT DO NOTHING;`
	);
}
out.push("");

out.push(`-- ${EVENTS.length} events`);
for (const e of EVENTS) {
	out.push(
		`INSERT INTO events (slug, title, starts_at, ends_at, location, excerpt, body, banner_url, status, quota, remaining_slots, price_normal, category) VALUES (` +
			[
				lit(e.slug),
				lit(e.title),
				lit(e.startsAt),
				lit(e.endsAt),
				lit(e.location),
				lit(e.excerpt),
				lit(e.body),
				lit(e.bannerUrl),
				lit(e.status),
				num(e.quota),
				num(e.remainingSlots),
				num(e.priceNormal),
				lit(e.category)
			].join(", ") +
			`);`
	);
}
out.push("");

out.push("-- event_categories join rows");
for (const e of EVENTS) {
	for (const catSlug of e.categorySlugs) {
		out.push(
			`INSERT INTO event_categories (event_id, category_id) ` +
				`SELECT ev.id, ca.id FROM events ev, categories ca ` +
				`WHERE ev.slug = ${lit(e.slug)} AND ca.slug = ${lit(catSlug)} ON CONFLICT DO NOTHING;`
		);
	}
}
out.push("");

if (!EVENTS_ONLY) {
	out.push("-- demo announcement");
	out.push(
		`INSERT INTO announcements (title, body) VALUES (${lit("Welcome to PKUBersua")}, ${lit("This is a test announcement inserted by the seed script.")});`
	);
	out.push("");
}

out.push("-- summary");
out.push(
	"SELECT (SELECT count(*) FROM events) AS events, (SELECT count(*) FROM categories) AS categories, (SELECT count(*) FROM event_categories) AS joins;"
);

console.log(out.join("\n"));
